"""Adicionando tombamento e localizacao

Revision ID: 42ea8fd75b10
Revises: 
Create Date: 2026-01-05 07:59:04.482417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ea8fd75b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tombamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('localizacao', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.drop_column('localizacao')
        batch_op.drop_column('tombamento')

    # ### end Alembic commands ###
